remove useless double brackets

diff --git a/maxentropy b/maxentropy
--- a/maxentropy
+++ b/maxentropy
@@ -11,7 +11,7 @@ SPECIESLIST=(human drosophila)
 FOLDERNAMES=(MaxEnt_Human MaxEnt_Drosophila)
 SEP="\t"
 
-HEADER="no"	#default: no header: keep 
+HEADER="no" #default: no header: keep 
 
 ############################ define usage / help function
 usage(){
@@ -76,9 +76,9 @@ containsElement(){
 ############################ parse arguments
 
 if [ $# -lt 1 ];then
-	echo "Error, please give arguments"
-	echo "For help, type: $(basename $0) -h"
-	exit 1
+	echo "Error, please give arguments">&2
+	echo "For help, type: $(basename $0) -h">&2
+	exit
 fi
 
 # put colon ":" after arguments that need a value in a variable. Ex: the flag -h don't need a value. same for V and A
@@ -92,15 +92,15 @@ while getopts "i:d:a:s:o:t:VAhH" OPTION; do
 		o) OUT="$OPTARG";;
 		H) HEADER="yes";;
 		t) SEP="$OPTARG";;
-		V) echo $VERSION; exit 1;;
-		A) echo $AUTHOR;  exit 1;;
-		h) usage; exit 1;;
+		V) echo $VERSION>&2; exit;;
+		A) echo $AUTHOR>&2;  exit;;
+		h) usage; exit;;
 	esac
 done
 
 ######## tests before run
-# test if species is in list of available species, else print error and exit 1
-! containsElement "$SPECIES" "${SPECIESLIST[@]}" && echo "$SPECIES is not in available species list: ${SPECIESLIST[@]}" && exit 1
+# test if species is in list of available species, else print error and exit
+! containsElement "$SPECIES" "${SPECIESLIST[@]}" && echo "$SPECIES is not in available species list: ${SPECIESLIST[@]}">&2 && exit
 
 
 # check script folder
@@ -136,8 +136,8 @@ cd $CUR
 
 # check that input file exist
 if [ ! -e "$IN" ];then
-	echo "Error, infile not found: '$IN'"
-    exit 1
+	echo "Error, infile not found: '$IN'">&2
+    exit
 fi
 
 # if oufile not set by options, make the default output name
@@ -148,8 +148,8 @@ fi
 #check for index
 if [ $indexCol5ss ];then
 	if [ $indexCol3ss ];then
-		echo "Error: please choose donor or acceptor scoring (give -a or -d with the index in file)"
-		exit 1
+		echo "Error: please choose donor or acceptor scoring (give -a or -d with the index in file)">&2
+		exit
 	else
 		TODO="donor"
 	fi
@@ -157,31 +157,31 @@ else
 	if [ $indexCol3ss ];then
 		TODO="acceptor"
 	else
-		echo "Error: please choose donor or acceptor scoring (give -a or -d with the index in file)"
-		exit 1
+		echo "Error: please choose donor or acceptor scoring (give -a or -d with the index in file)">&2
+		exit
 	fi
 fi
-
+>&2
 #check for Ns in the sequences
-if [[ "$HEADER" == "yes" ]];then
+if [ "$HEADER" == "yes" ];then
 	if [ $indexCol5ss ];then #check n N in donor
 		NB=$(cut -f $indexCol5ss $IN | tail -n +2 | grep -in N | wc -l)
-		if [ $NB -gt 0 ]; then echo "error: there are some N on your sequences: $NB";exit; fi
+		if [ $NB -gt 0 ]; then echo "error: there are some N on your sequences: $NB">&2;exit; fi
 	fi
 	if [ $indexCol3ss ];then #check n N in donor
 		NB=$(cut -f $indexCol3ss $IN | tail -n +2 | grep -in N | wc -l)
-		if [ $NB -gt 0 ]; then echo "error: there are some N on your sequences: $NB";exit; fi
+		if [ $NB -gt 0 ]; then echo "error: there are some N on your sequences: $NB">&2;exit; fi
 	fi
 fi
 
-if [[ "$HEADER" == "no" ]];then
+if [ "$HEADER" == "no" ];then
 	if [ $indexCol5ss ];then #check n N in donor
 		NB=$(cut -f $indexCol5ss $IN | grep -in N | wc -l)
-		if [ $NB -gt 0 ]; then echo "error: there are some N on your sequences: $NB";exit; fi
+		if [ $NB -gt 0 ]; then echo "error: there are some N on your sequences: $NB">&2;exit; fi
 	fi
 	if [ $indexCol3ss ];then #check n N in donor
 		NB=$(cut -f $indexCol3ss $IN | grep -in N | wc -l)
-		if [ $NB -gt 0 ]; then echo "error: there are some N on your sequences: $NB";exit; fi
+		if [ $NB -gt 0 ]; then echo "error: there are some N on your sequences: $NB">&2;exit; fi
 	fi
 fi
 
@@ -197,10 +197,10 @@ if [ $TODO == "donor" ];then
 	#check length of sequence
 	line=$(tail -n 1 "five" | cut -f $indexCol5ss)
 	SIZE=${#line}
-	if [ $SIZE -ne 9 ];then echo "Error: your donor sequence has a size != 9 ($SIZE)";rm "five"; exit 1; fi
+	if [ $SIZE -ne 9 ];then echo "Error: your donor sequence has a size != 9 ($SIZE)">&2;rm "five"; exit; fi
 	#check GT
 	GT=${line:3:2}
-	if [ $GT != "GT" ];then echo "Error: your donor sequence does not have the correct GT ($GT)"; exit 1; fi
+	if [ $GT != "GT" ];then echo "Error: your donor sequence does not have the correct GT ($GT)">&2; exit; fi
 	#check number of lines
 	REF=$(wc -l <$IN)
 	if [ "$HEADER" == "yes" ]; then
@@ -209,9 +209,8 @@ if [ $TODO == "donor" ];then
 		COUNT=$(( $(wc -l <"five") ))
 	fi
 	if [ $REF -ne $COUNT ];then
-		echo "Error in MaxEnt: bad number of lines: five - $IN (check GT | skip first line) exit!"
-		#rm "five"
-		exit 1
+		echo "Error in MaxEnt: bad number of lines: five - $IN (check GT | skip first line) exit!">&2
+		exit
 	fi
 	#move
 	mv "five" "$SCRIPTPATH"
@@ -246,10 +245,10 @@ if [ $TODO == "acceptor" ];then
 	#check length of sequence
 	line=$(tail -n 1 "three" | cut -f $indexCol3ss)
 	SIZE=${#line}
-	if [ $SIZE -ne 23 ];then echo "Error: your acceptor sequence has a size != 23 ($SIZE) exit! "; rm "three"; exit 1; fi
+	if [ $SIZE -ne 23 ];then echo "Error: your acceptor sequence has a size != 23 ($SIZE) exit! ">&2; rm "three"; exit; fi
 	#check AG
 	AG=${line:18:2}
-	if [ $AG != "AG" ];then echo "Error: your donor sequence does not have the correct AG ($AG) exit!"; exit 1; fi
+	if [ $AG != "AG" ];then echo "Error: your donor sequence does not have the correct AG ($AG) exit!">&2; exit; fi
 	#check number of lines
 	REF=$(wc -l <$IN)
 	if [ "$HEADER" == "yes" ]; then
@@ -258,9 +257,9 @@ if [ $TODO == "acceptor" ];then
 		COUNT=$(( $(wc -l <"three") ))
 	fi
 	if [ $REF -ne $COUNT ];then
-		echo "Error in MaxEnt: bad number of lines: three - $IN (check AG | skip first line) exit!"
+		echo "Error in MaxEnt: bad number of lines: three - $IN (check AG | skip first line) exit!">&2
 		#rm "three"
-		exit 1
+		exit
 	fi
 	#move
 	mv "three" "$SCRIPTPATH"
