update: new spider

diff --git a/spider b/spider
--- a/spider
+++ b/spider
@@ -1,46 +1,89 @@
 #!/bin/bash
 #coding:utf-8
-
+set -e
 #==============================
 #	VARIABLES
 #==============================
-VERSION="1.0"
+VERSION="1.1"
 AUTHOR="Author: Gildas Lepennetier - gildas.lepennetier@hotmail.fr"
 COPY="Copyright 2015 LEPENNETIER Gildas"
 CREATION="22 March 2015"
-
-
 #==============================
 #	FUNCTIONS
 #==============================
-
-# usage function
+# to print the help
 usage(){
 cat << EOF
-	usage: $(basename $0) url [-h]
+	usage: $(basename $0) [options]
 	
-	A spider for the big web.
-	
-	DESCRIPTION
-	
-	Explore web domains from a todo file ($todo)
-	Extract external and internal links
-	Create a domains database ($mydb)
-	Keep track of explored links ($explored)
-	Can crawl with different depth (default: $DEPTH)
-	Stop if taking too long (max time: $maxtime)
-	
-	ARGUMENTS
+	A spider written in bash and based on curl.
 
-	-h		print help
-	
------------------------
-	$AUTHOR
-	Version $VERSION - Creation $CREATION
-	$COPY
+	-h	Display help
+	-d	Domain to explore
+
+
+$AUTHOR
+Version $VERSION - Creation $CREATION
+$COPY
 EOF
 }
 
+	# get a domain name from a link
+baseDomain(){
+	prefix=${1%%//*}
+	suffix=${1#*//}
+	domain=${suffix%%/*}
+	echo "$prefix//$domain"
+}
+	# get the page in text
+#curl $1 --silent --compressed --fail --max-time 15 --retry 3 --retry-delay 10
+
+	#get html status
+#wget --spider -S "$url" 2>&1 | grep "HTTP/" | awk '{print $2}'
+# grep the links from a text - remove the balise with sed
+
+extractLinks(){
+	while read data;do 
+	echo $data | 
+	grep -E "href=['\"]{1}([^ #&?]*)['\"]{1}" --only-matching --no-messages | 
+	sed -e "s/href=//g" -e "s/'//g" -e "s/\"//g" -e "s/\/$//g"
+	done
+}
+
+if [ $# -eq 0 ];then usage; exit; fi
+# option parser
+while getopts "l:h" OPTION; do
+	case $OPTION in
+		h) usage;exit
+		;;
+		l) url="$OPTARG"
+		;;
+	esac
+done
+
+
+#==============================
+#	MAIN
+#==============================
+domain=$(getBaseDomain $url)
+
+
+exit
+
+
+[ $(urlExists $url) ] || echo "url does not exist: $url"
+[ $(urlExists $domain) ] || echo "domain does not exist neither: $domain"
+exit
+
+page=$(getPage $url)
+links=$(echo $page | getLinks)
+echo "links:"
+echo $links
+
+exit
+#==============================
+#	MAIN - old
+#==============================
 # get list of links from a url, url is $1
 getLinksFromURL(){ curl $1 --silent --compressed --fail --max-time 15 --retry 3 --retry-delay 10 | grep -E "href=['\"]{1}([^ #&?]*)['\"]{1}" --only-matching --no-messages | sed -e "s/href=//g" -e "s/'//g" -e "s/\"//g" -e "s/\/$//g";}
 
@@ -59,33 +102,7 @@ echo $data | grep -e "$1" #for the link fully made
 echo $data | grep -ve "$1"|grep -ve "http://" -ve "https://" -ve "ftp://"|sed '1s/^\///'|awk "{print \"$1\" \"/\" \$0}"
 done;}
 
-# get a domain name from a link
-getBaseDomain(){
-prefix=${1%%//*}
-suffix=${1#*//}
-domain=${suffix%%/*}
-echo "$prefix//$domain"
-}
 
-# use curl to know if url exist
-urlExists(){ curl --output /dev/null --silent --head --fail "$1";}
-
-# select 1 random lines from a file, file is $1
-getRandom(){ sort -R "$1"|head -n 1;}
-
-
-while getopts "h" OPTION; do
-	case $OPTION in
-		h) usage; exit 1; ;;
-	esac
-done
-exit
-
-#==============================
-#	MAIN
-#==============================
-
-url=$1
 
 #check given url, if ok add to todo list
 if urlExists "$url"; then echo "$url" >> "$todo"; else echo -e "No url / Bad url\nPlease give an url as first argument, of -h for help"; fi
